<div class="row">
  <div class="col-8 mb-3">
    <div class="input-group">
      <input type="text" class="form-control" id="search-input" placeholder="Procurar clientes" aria-label="Recipient's username" aria-describedby="button-addon2">
      <button class="btn-outline-primary">Pesquisar...</button>
    </div>
  </div>
  <div class="col-4">
    <a href="<?= route('clients.new') ?>" class="btn link-button">
      <i class="bi bi-journal-plus fs-1"></i>
      Novo Cliente
    </a>    
  </div>
</div>

<table class="table">
  <thead>
    <th>ID</th>
    <th>Nome</th>
    <th>CPF</th>
    <th>Email</th>
  </thead>
  <tbody>
    <?php foreach ($clients as $client) : ?>
      <tr>
        <td><a href="<?= route('clients.show', ['id' => $client->id]) ?>"><?= $client->id ?></a></td>
        <td><?= $client->name ?></td>
        <td><?= maskCPF($client->cpf) ?></td>
        <td><?= $client->email ?></td>
        <td>
            <div class="d-flex flex-row-reverse">
                <form action="<?= route('clients.destroy', ['id' => $client->id]) ?>" method="POST" class="m-0">
                    <input type="hidden" name="_method" value="DELETE">
                    <button type="submit" class="btn btn-link"><i class="bi bi-trash3"></i></button>
                </form>
                <a href="<?= route('clients.edit', ['id' => $client->id]) ?>" class="btn btn-link pe-0">
                    <i class="bi bi-pencil-square"></i>
                </a>
            </div>
        </td>
      </tr>
      <?php endforeach; ?>
  </tbody>
</table>

<?php $paginator->renderPagesNavigation(); ?>