<div class="container mt-5 d-flex row justify-content-center align-items-center h-100">
  <div class="row">
    <div class="col-12 mb-3 ml-4">
      <a href="<?= route('clients.index') ?>" class="btn btn-secondary">
        <i class="bi bi-chevron-left"></i> Voltar
      </a>
    </div>
  </div>
  <div class="card col-10">
    <div class="card-body">
      <h4 class="card-title"><?= $client->name ?></h4>
      <p class="card-text"><?= $client->email ?></p>
      <p class="card-text"><?= $client->cpf ?></p>
    </div>
  </div>
</div>