<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tax Tracker</title>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="/assets/js/application.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="/assets/css/application.css">
</head>

<body class="">
    <nav class="navbar">
        <div class="container-fluid d-flex flex-row justify-content-between mx-4">
            <a class="navbar-brand" href="<?= route('index') ?>">Tax Tracker</a>
            
            <div class="d-flex flex-row align-items-center gap-3">
                <img id="img_preview" class="avatar-preview img-thumbnail" src="<?= $this->currentUser()->avatar()->path() ?>" alt="avatar" >
                <?php if ($this->current_user) : ?>
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" aria-expanded="false">
                            <?= $this->current_user->email ?>
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="<?= route('accountants.profile') ?>">Perfil</a>                      
                            <a class="dropdown-item" href="<?= route('accountants.logout') ?>">Sair</a>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </nav>
    <main class="container-fluid">
        <div class="row">
            <aside class="col-auto sidebar">
                <div class="col-sm-auto sticky-top">
                    <div class="d-flex flex-sm-column flex-row flex-nowrap align-items-center sticky-top mt-1">
                        <ul class="nav nav-pills nav-flush flex-sm-column flex-row flex-nowrap mb-auto mx-auto text-center align-items-center">
                            <li class="nav-item">
                                <a href="<?= route('index') ?>" class="nav-link py-2 px-1" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Página Inicial">
                                    <i class="bi-house fs-1"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="<?= route('declarations.new') ?>" class="nav-link py-2 px-1" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Iniciar Nova Declaração">
                                    <i class="bi-plus-lg fs-1"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="<?= route('declarations.pending') ?>" class="nav-link py-2 px-1" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Minhas Declarações Pendentes">
                                    <i class="bi-view-list fs-1"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="<?= route('declarations.finished') ?>" class="nav-link py-2 px-1" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Minhas Declarações Finalizadas">
                                    <i class="bi-list-check fs-1"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="<?= route('declarations.my') ?>" class="nav-link py-2 px-1" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Todas as minhas declarações">
                                    <i class="bi-archive fs-1"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="<?= route('clients.index') ?>" class="nav-link py-2 px-1" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Clientes">
                                    <i class="bi-person-vcard fs-1"></i>
                                </a>
                            </li>
                            <?php if ($this->current_user->role_id > 1): ?>
                                <li class="nav-item">
                                    <a href="<?= route('declarations.all') ?>" class="nav-link py-2 px-1" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Todas as Declarações que Supervisiono">
                                        <i class="bi-archive-fill fs-1"></i>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="<?= route('accountants.all') ?>" class="nav-link py-2 px-1" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Contadores que Supervisiono">
                                        <i class="bi-person fs-1"></i>
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if ($this->current_user->role_id > 2): ?>
                                <li class="nav-item">
                                    <a href="<?= route('accountants.new') ?>" class="nav-link py-2 px-1" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Cadastrar Novo Contador">
                                        <i class="bi-person-plus fs-1"></i>
                                    </a>
                                </li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
            </aside>
            <section id="main-content" class="col">

                <?php require '_flash_message.phtml'; ?>

                <header class="mb-3">
                    <h1>
                        <?= $title ?>
                    </h1>
                </header>

                <?php require $view ?>

            </section>
        </div>
    </main>
</body>

</html>